---
- name: Start Z-Wave JS UI
  block:
    - name: Create Z-Wave JS UI Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ zwave_js_directory }}"
    
    - name: Z-Wave JS UI Docker Container
      docker_container:
        name: "{{ zwave_js_container_name }}"
        image: "{{ zwave_js_docker_image }}"
        pull: true
        volumes:
          - "{{ zwave_js_directory }}/usr/src/app/store:/store:rw"
        ports: 
          - "{{ zwave_js_ui_port }}:8091"
          - "{{ zwave_js_ws_port }}:3000"
        restart_policy: unless-stopped
        devices: "{{ zwave_js_serial_device }}:/dev/zwave"
        env:
          SESSION_SECRET: "{{ zwave_js_secret }}"
          ZWAVEJS_EXTERNAL_CONFIG: "{{ zwave_js_directory }}/usr/app/store/.config-db"
          TZ: "{{ ansible_nas_timezone }}"
        memory: "{{ zwave_js_memory }}"
  when: zwave_js_enabled is true

- name: Stop Z-Wave JS UI
  block:
    - name: Stop Z-Wave JS UI
      docker_container:
        name: "{{ zwave_js_container_name }}"
        state: absent
  when: zwave_js_enabled is false
